# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bfc70a3256eee6c83325ef3a4cb4885e4db63a1d8e3124ce0da82fd1fc72fe75b46a5e0f7461365f1b4f51704dc6ae4ec57d333416086eae05edf6add8a6774

test:
  secret_key_base: 145ebfeed158e3c072867f0d13fc9ac013144a8de6bdb2409b10d4c742b467d984d4a4c0df51a4fcc9ceb4f509f987915790fd9efcdd39944ee69bcd5cef1302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
